version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_DB=mycv
      - POSTGRES_USER=mycv_dbuser
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/backend/logs
    depends_on:
      - postgres

volumes:
  postgres-data: