alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: cv.streckeisen.dev
  type: PRIMARY
envs:
- key: MYCV_DATASOURCE
  scope: RUN_AND_BUILD_TIME
  value: jdbc:postgresql://db-postgresql-fra1-45654-do-user-17705918-0.e.db.ondigitalocean.com:25061/my-cv-app?sslmode=require
- key: MYCV_DB_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: mycv-db-user
- key: SPRING_PROFILES_ACTIVE
  scope: RUN_AND_BUILD_TIME
  value: prod
- key: MYCV_DB_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:UbY5XDYo6af2b+9ZIC9vbOJsfBtZZBwH:zGJDGQSEVu3wYQ0fYcGvShp7FlFgus11rNk67BPRGxjYlt3myMm74Q==]
- key: JWT_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:d5xmFomXzftP2JpRHetK32NPNewjolOl:Va+iT2DVqm8e9wN0Gp9ECoBWFE6uPWXnjZP5sOLH1d2rdINw2r/PDzYyMPcRGc7efQxXkaEHSTcyIlf1Kjvo6gG3wY3DP7OwnEXYv7Q8tSYOiGtYwxYhjrlk4uYjE5eUVyvfTdf5rs0/M7By43fJaVpx84v9YJG90MCXOQfs4B8C7kXl7au2BwYSLW4ICVsslfhjCaJTobQWQXNGebG5ocFrA4ii9pS3qWqz6yAuCBOITRpI/rXnpQKM548=]
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: my-cv
    match:
      path:
        prefix: /
name: my-cv-app
region: fra
services:
- http_port: 8080
  image:
    registry: lstreckeisen
    registry_credentials: EV[1:SZtHlCRh25xCY3lgXqdDKGg+1Uf2qOT5:xUH8j/qTcMTJHA8bxhgPo7mUCZvxZKIUasaVApbs2qcRz/miKM2eKET3FlwDagScTgdj4HgC]
    registry_type: DOCKER_HUB
    repository: my-cv
    tag: latest
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: my-cv
