spring.datasource:
  url: jdbc:postgresql://localhost:5432/mycv
  username: postgres
  password: postgres

security.jwt.secret: wHqRTjE8tXtgm/zhvn1qmmxLkcA+MvjnbX0aLkNhLm4=

logging:
  file.name: ./logs/mycv.log

PROFILE_PICTURE_FOLDER: ./profile/