spring:
  application.name: "MyCV"
  datasource:
    url: ${MYCV_DATASOURCE}
    username: ${MYCV_DB_USERNAME}
    password: ${MYCV_DB_PASSWORD}
    hikari.maximum-pool-size: 10

  jpa:
    generate-ddl: false

  liquibase.change-log: db/changelog/db.changelog-master.xml

  servlet.multipart:
    max-request-size: 2MB
    max-file-size: 2MB

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
              - repo
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/github"
            authorization-grant-type: authorization_code
            client-name: GitHub

security.jwt:
  secret: ${JWT_SECRET}
  access.expiration-time: 3600000
  refresh.expiration-time: 432000000

logging:
  file.name: /app/logs/mycv.log
  include-application-name: false
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 5MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  url-expiration: 300

frontend:
  base-url: https://mycvhub.ch/ui