name: MyCV CI/CD pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '21'

    - name: Build frontend
      working-directory: frontend
      run: |
        npm ci
        npm run build

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-artifact
        path: frontend/dist
  
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '21'
        distribution: temurin

    - name: Build backend
      working-directory: backend
      run: ./mvnw clean package
    
    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-artifact
        path: backend/target/mycv.jar

  #deploy:
  #  if: github.ref == 'refs/heads/main'
  #  runs-on: ubuntu-latest
  #  needs:
  #    - build-frontend
  #    - build-backend
  #  
  #  steps:
  #  - name: Checkout code
  #    uses: actions/checkout@v4
#    
#    - name: Download frontend artifact
#      uses: actions/download-artifact@v4
#      with:
#        name: frontend-artifact
#        path: frontend/dist
#    
#    - name: Download backend artifact
#      uses: actions/download-artifact@v4
#      with:
#        name: backend-artifact
#        path: backend/target/mycv.jar
#    
#    - name: Setup Docker Buildx
#      uses: docker/setup-buildx-action@v3.6.1
#    
#    - name: Login to Docker Hub
#      uses: docker/login-action@v3.3.0
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#    
#    - name: Build & Push Docker images
#      uses: docker/build-push-action@v6.7.0
#      with:
#        context: .
#        push: true
#        tags: lstreckeisen/my-cv:latest