name: MyCV CI/CD pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Build frontend
      working-directory: frontend
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-artifact
        path: frontend/dist/
  
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin

    - name: Build backend
      working-directory: backend
      run: ./mvnw clean package
    
    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-artifact
        path: backend/target/mycv.jar
  
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs:
      - build-frontend
      - build-backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-artifact
        path: ./frontend/dist
    
    - name: Download backend artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-artifact
        path: ./backend/target
    
    - name: Build Docker image
      run: |
        docker build -t my-cv:${{ github.sha }} .
    
    - name: Log in to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag my-cv:${{ github.sha }} lstreckeisen/my-cv:${{ github.sha }}
        docker push lstreckeisen/my-cv:${{ github.sha }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - docker-build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Update DigitalOcean specs with docker image tag
      run: |
        sed -i 's/latest/${{ github.sha }}/' .do/my-cv-app.yaml
    
    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action/deploy@v2
      with:
        project_id: 36885f94-3294-46d5-abe9-48952ce7bbfd
        token: ${{ secrets.DO_ACCESS_TOKEN }}
        app_spec_location: .do/my-cv-app.yaml
        print_build_logs: true
        print_deploy_logs: true
