name: Deploy

on:
  workflow_run:
    workflows: ["Build pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download frontend artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: frontend-artifact
          path: frontend/dist
      
      - name: Download backend artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: backend-artifact
          path: backend/target/mycv.jar
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: lstreckeisen/my-cv:latest
